student_name=input("enter the student name")
roll_number=int(input("enter the roll number of student"))
cgpa= float(input("enter cgpa here:"))
print("your name is",student_name)
print("your roll number is",roll_number+1)
print("your cgpa is",cgpa*10,"%")